onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider tb_top
add wave -noupdate /tb_top/sclk
add wave -noupdate /tb_top/s_rst_n
add wave -noupdate /tb_top/sdram_clk
add wave -noupdate /tb_top/sdram_cke
add wave -noupdate /tb_top/sdram_cs_n
add wave -noupdate /tb_top/sdram_cas_n
add wave -noupdate /tb_top/sdram_ras_n
add wave -noupdate /tb_top/sdram_we_n
add wave -noupdate /tb_top/sdram_bank
add wave -noupdate /tb_top/sdram_addr
add wave -noupdate /tb_top/sdram_dqm
add wave -noupdate /tb_top/sdram_dq
add wave -noupdate /tb_top/rs232_tx
add wave -noupdate -divider top
add wave -noupdate /tb_top/top_inst/sclk
add wave -noupdate /tb_top/top_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/rs232_rx
add wave -noupdate /tb_top/top_inst/rs232_tx
add wave -noupdate /tb_top/top_inst/sdram_clk
add wave -noupdate /tb_top/top_inst/sdram_cke
add wave -noupdate /tb_top/top_inst/sdram_cs_n
add wave -noupdate /tb_top/top_inst/sdram_cas_n
add wave -noupdate /tb_top/top_inst/sdram_ras_n
add wave -noupdate /tb_top/top_inst/sdram_we_n
add wave -noupdate /tb_top/top_inst/sdram_bank
add wave -noupdate /tb_top/top_inst/sdram_addr
add wave -noupdate /tb_top/top_inst/sdram_dqm
add wave -noupdate /tb_top/top_inst/sdram_dq
add wave -noupdate /tb_top/top_inst/rx_data
add wave -noupdate /tb_top/top_inst/tx_trig
add wave -noupdate /tb_top/top_inst/sdram_wr_trig
add wave -noupdate /tb_top/top_inst/sdram_rd_trig
add wave -noupdate /tb_top/top_inst/wfifo_wr_en
add wave -noupdate /tb_top/top_inst/wfifo_data
add wave -noupdate /tb_top/top_inst/wfifo_rd_en
add wave -noupdate /tb_top/top_inst/wfifo_rd_data
add wave -noupdate /tb_top/top_inst/rfifo_wr_data
add wave -noupdate /tb_top/top_inst/rfifo_wr_en
add wave -noupdate /tb_top/top_inst/rfifo_rd_data
add wave -noupdate /tb_top/top_inst/rfifo_rd_en
add wave -noupdate /tb_top/top_inst/rfifo_empty
add wave -noupdate -divider uart_rx
add wave -noupdate /tb_top/top_inst/uart_rx_inst/sclk
add wave -noupdate /tb_top/top_inst/uart_rx_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rs232_rx
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_data
add wave -noupdate /tb_top/top_inst/uart_rx_inst/po_flag
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_r1
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_r2
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_r3
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_flag
add wave -noupdate /tb_top/top_inst/uart_rx_inst/baud_cnt
add wave -noupdate /tb_top/top_inst/uart_rx_inst/bit_flag
add wave -noupdate /tb_top/top_inst/uart_rx_inst/bit_cnt
add wave -noupdate /tb_top/top_inst/uart_rx_inst/rx_neg
add wave -noupdate -divider cmd_decode
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/sclk
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/uart_flag
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/uart_data
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/wr_trig
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/rd_trig
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/wfifo_wr_en
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/wfifo_data
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/rec_num
add wave -noupdate /tb_top/top_inst/cmd_decode_inst/cmd_reg
add wave -noupdate -divider uart_tx
add wave -noupdate /tb_top/top_inst/uart_tx_inst/sclk
add wave -noupdate /tb_top/top_inst/uart_tx_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/uart_tx_inst/rs232_tx
add wave -noupdate /tb_top/top_inst/uart_tx_inst/rfifo_empty
add wave -noupdate /tb_top/top_inst/uart_tx_inst/rfifo_rd_en
add wave -noupdate /tb_top/top_inst/uart_tx_inst/rfifo_rd_data
add wave -noupdate /tb_top/top_inst/uart_tx_inst/tx_data_r
add wave -noupdate /tb_top/top_inst/uart_tx_inst/tx_flag
add wave -noupdate /tb_top/top_inst/uart_tx_inst/baud_cnt
add wave -noupdate /tb_top/top_inst/uart_tx_inst/bit_flag
add wave -noupdate /tb_top/top_inst/uart_tx_inst/bit_cnt
add wave -noupdate /tb_top/top_inst/uart_tx_inst/tx_trig
add wave -noupdate /tb_top/top_inst/uart_tx_inst/tx_trig_r1
add wave -noupdate -divider sdram_top
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sclk
add wave -noupdate /tb_top/top_inst/sdram_top_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_clk
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_cke
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_cs_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_cas_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_ras_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_we_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_bank
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_dqm
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_dq
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_trig
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_trig
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wfifo_rd_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wfifo_rd_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rfifo_wr_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rfifo_wr_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sd_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/flag_init_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/init_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/init_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/state
add wave -noupdate /tb_top/top_inst/sdram_top_inst/ref_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/flag_ref_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/ref_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/ref_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/ref_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/flag_wr_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_bank_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/wr_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/flag_rd_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/rd_bank_addr
add wave -noupdate -divider sdram_write
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/sclk
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/flag_wr_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/ref_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_trig
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/bank_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wfifo_rd_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wfifo_rd_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/flag_wr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/state
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/flag_act_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/flag_pre_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/sd_row_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/burst_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/burst_cnt_t
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/wr_data_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/act_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/break_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/col_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/row_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_write_inst/col_addr
add wave -noupdate -divider sdram_read
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/sclk
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/s_rst_n
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/flag_rd_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/ref_req
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_trig
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/sdram_dq
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_cmd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/bank_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rfifo_wr_en
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rfifo_wr_data
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rfifo_wr_en_t
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rfifo_wr_en_tt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/flag_rd
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/state
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/flag_act_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/flag_pre_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/sd_row_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/burst_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/burst_cnt_t
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/rd_data_end
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/act_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/break_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/col_cnt
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/row_addr
add wave -noupdate /tb_top/top_inst/sdram_top_inst/sdram_read_inst/col_addr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {153128834 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {336 us}
